//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SWTUpdate.rc
//
#define IDP_OLE_INIT_FAILED			100
#define IDD_ABOUTBOX                    100
#define IDD_CHECKDLG                    101
#define IDD_OPTION                      102
#define IDD_COPYDLG                     103
#define IDD_WRITEDIRFILE                104
#define ID_STATUSBAR_PANE1			120
#define ID_STATUSBAR_PANE2			121
#define IDS_STATUS_PANE1			122
#define IDS_STATUS_PANE2			123
#define IDS_TOOLBAR_STANDARD		124
#define IDS_TOOLBAR_CUSTOMIZE		125
#define ID_VIEW_CUSTOMIZE			126
#define IDR_MAINFRAME                   128
#define IDR_TREECONTEXTMENU             130
#define IDR_LISTCONTEXTMENU             131
#define IDD_FILEPROPERTY                131
#define IDB_IMAGELIST                   132
#define IDD_STARTCOPY                   132
#define IDB_STATEIMAGELIST              133
#define ID_UPDATE_MERGE                 138
#define IDR_AVI_COPY                    139
#define IDR_AVI_SEARCH                  140
#define IDD_LISTADMIN                   141
#define IDD_GLOBALOPTIONS               142
#define IDC_S_CHECKDIR                  1000
#define IDC_E_ORIG                      1003
#define IDC_E_COPY                      1004
#define IDC_E_ORIGFILE                  1005
#define IDC_E_COPYFILE                  1007
#define IDC_E_EXCLUDEDIR                1009
#define IDC_E_EXCLUDEEXT                1010
#define IDC_PROGRESS_COPY               1010
#define IDC_S_SRCFILE                   1011
#define IDC_E_EXCLUDEFILES              1011
#define IDC_S_DESTFILE                  1012
#define IDC_R_USEDIR_ORIG               1012
#define IDC_R_USEDIR_ORIG2              1013
#define IDC_PROGRESS_COPYFILE           1013
#define IDC_B_ORIGFILE                  1014
#define IDC_R_USEDIR_COPY               1015
#define IDC_B_SELECT                    1015
#define IDC_E_FILE                      1016
#define IDC_R_USEDIR_COPY2              1016
#define IDC_B_COPYFILE                  1017
#define IDC_E_DIR                       1017
#define IDC_B_WRITE                     1018
#define IDC_E_EXCHANGEDIR               1018
#define IDC_C_DOSTIME                   1019
#define IDC_C_ROUND2SEC                 1020
#define IDC_E_EXCHANGEFILE              1021
#define IDC_STOPCOUNT                   1021
#define IDC_NEW                         1021
#define IDC_C_SUMMERTIME                1022
#define IDC_LEFT_NAME                   1022
#define IDC_LEFT_DATE                   1023
#define IDC_B_ORIGDIR                   1023
#define IDC_LEFT_SIZE                   1024
#define IDC_VERSION                     1024
#define IDC_B_COPYDIR                   1024
#define IDC_C_ORIGRDONLY                1025
#define IDC_RIGHT_DATE                  1026
#define IDC_C_COPYRDONLY                1026
#define IDC_RIGHT_SIZE                  1027
#define IDC_E_CONFIRMTIMEOUT            1027
#define IDC_NEXTOP                      1028
#define IDC_C_SETRDONLY                 1029
#define IDC_E_1LVLSUBDIR                1030
#define IDC_C_ASKOLDER                  1031
#define IDC_C_ORIG_IGNOREMISSING        1032
#define IDC_C_COPY_IGNOREMISSING        1033
#define IDC_SENDMAIL                    1034
#define IDC_C_STOPONERROR               1034
#define IDC_COPYLOGDIR                  1035
#define IDC_EXCLUDEDIR                  1036
#define IDC_AVI_COPY                    1037
#define IDC_EXCLUDEEXT                  1037
#define IDC_AVI_SEARCH                  1038
#define IDC_EXCLUDEFILE                 1038
#define IDC_TIME_FILE                   1039
#define IDC_1LVLSUBDIR                  1039
#define IDC_TIME_TOTAL                  1040
#define IDC_TOTAL_FILES                 1042
#define IDC_TOTAL_SIZE                  1043
#define IDC_REMAINING_FILES             1044
#define IDC_REMAINING_SIZE              1045
#define IDC_ELLAPSEDTIME                1046
#define IDC_LIST                        1046
#define IDC_DELETE                      1047
#define IDC_SPEEDTOTAL                  1047
#define IDC_EDIT                        1048
#define IDC_E_COMPAREPRG                1048
#define IDC_SPEEDCURRENT                1049
#define IDC_COMPAREOPTION               1049
#define IDC_RADIO2                      1050
#define IDC_COMPAREOPTION_CONTENT       1050
#define IDC_COMPAREOPTION_FD_CONTENT    1051
#define ID_CHECK                        32771
#define ID_ORG2COPY                     32774
#define ID_COPY2ORG                     32775
#define ID_DOACTION                     32776
#define ID_OPTIONS                      32777
#define ID_UNDOCOPY                     32780
#define ID_WRITEDIRFILE                 32781
#define ID_CHECKDIR                     32782
#define ID_COPYEXCHANGE                 32784
#define ID_SHOWDIFF                     32786
#define ID_SHELLEXECLEFT                32787
#define ID_SHELLEXECRIGHT               32788
#define ID_UPDATE_FILEPROPERTIES        32791
#define ID_ADDEXCLUDEFILE               32798
#define ID_ADDEXCLUDEEXTENSION          32800
#define ID_ADDEXCLUDEDIRECTORY          32802
#define ID_FILE_OPTIONS                 32813

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
