
name: Build Docker Image for Sudoku Solve Server

env:
  ContainerName: sudokusolveserver           # Name of he (docker-)container
  SolutionPath: Src                              # sub-directory of sln file location
  SolutionName: Sudoku.sln                       # Replace with your solution name, i.e. MyWpfApp.sln.
  AppProject: Solve.Server/Solve.Server.csproj   # Replace with the path to your app project, i.e. MyWpfApp\MyWpfApp.csproj.

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.SolutionPath }}
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:Src"
          file: ./Solve.Server/Dockerfile
          #platforms: linux/amd64,linux/arm/v7
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.ContainerName}}:latest
